# Generated by Django 2.2.2 on 2019-08-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='是否已检查'),
        ),
    ]
