# Generated by Django 2.2.2 on 2019-06-23 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='error_num',
            field=models.IntegerField(default=0, verbose_name='出错次数'),
        ),
        migrations.CreateModel(
            name='Spider_Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Error_content', models.CharField(max_length=500, verbose_name='报错内容')),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vei.Spider', verbose_name='出错爬虫')),
            ],
            options={
                'verbose_name': '脚本报错',
                'verbose_name_plural': '脚本报错',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='评论内容')),
                ('comments_name', models.CharField(max_length=20, verbose_name='评论人')),
                ('comments_email', models.CharField(max_length=100, verbose_name='评论邮箱')),
                ('comments_img', models.ImageField(upload_to='comments_imgs/')),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vei.Spider', verbose_name='评论对象')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
