# Generated by Django 2.2.2 on 2019-07-13 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_ip', models.CharField(max_length=30, verbose_name='代理IP')),
                ('proxy_type1', models.CharField(choices=[(1, 'HTTP'), (2, 'HTTPS')], default=1, max_length=10, verbose_name='代理类型')),
                ('proxy_type2', models.CharField(choices=[(1, '未知'), (2, '高匿'), (3, '普匿')], default=1, max_length=10, verbose_name='代理类型')),
                ('proxy_place', models.CharField(max_length=100, verbose_name='地区')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
    ]
