# Generated by Django 2.2.2 on 2019-07-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vei', '0003_auto_20190713_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='proxy_type1',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('HTTP', 'HTTP')], default='HTTP', max_length=10, verbose_name='代理类型'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='proxy_type2',
            field=models.CharField(choices=[('未知', '未知'), ('高匿', '高匿'), ('普匿', '普匿')], default='未知', max_length=10, verbose_name='代理类型'),
        ),
    ]
