# Generated by Django 2.2.2 on 2019-07-13 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vei', '0004_auto_20190713_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_content', models.CharField(max_length=300, verbose_name='播报内容')),
                ('is_used', models.BooleanField(default=True, verbose_name='是否启用')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '播报',
                'verbose_name_plural': '播报',
            },
        ),
        migrations.CreateModel(
            name='Shuffling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='shuffling_imgs/', verbose_name='轮播图')),
                ('is_used', models.BooleanField(default=True, verbose_name='是否启用')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.AlterField(
            model_name='proxy',
            name='proxy_type1',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTP')], default='HTTP', max_length=10, verbose_name='代理类型'),
        ),
    ]
